name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Elixir ${{matrix.elixir}} on OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        # Earliest and latest supported of each, only, to avoid abusing GitHub's machinery:
        otp: ["21.3", "23.1"]
        elixir: ["1.8", "1.11"]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: gleam-lang/setup-erlang@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
      - uses: erlef/setup-elixir@v1.6.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Cache deps
        uses: actions/cache@v1.1.2
        env:
          cache-name: deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ env.cache-name }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ env.cache-name }}-
      - name: Cache _build
        uses: actions/cache@v1.1.2
        env:
          cache-name: _build
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ env.cache-name }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ env.cache-name }}-
      - name: mix deps.get
        run: |
          mix deps.get
          mix deps.unlock --unused
          mix deps.clean --unused
          git diff --exit-code mix.lock
      - name: mix compile (dev)
        run: |
          mix deps.compile
          mix compile
      - name: mix compile (test)
        run: |
          mix deps.compile
          mix compile
        env:
          MIX_ENV: test
      - name: mix test
        run: mix coveralls --trace
      - name: mix format
        run: |
          mix format
          git diff --exit-code mix.lock
      - name: mix credo
        run: mix credo --strict
      - run: mix docs
      - run: mix dialyzer
